comment_width = 120
edition = "2021"
format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
max_width = 120
normalize_comments = true
normalize_doc_attributes = true
reorder_imports = true
trailing_comma = "Vertical"
trailing_semicolon = true
wrap_comments = true