name: Build

on:
    pull_request:
    push:
        branches: [main, develop]

jobs:
    fnote:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Rust Toolchain
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: nightly
                  override: true
                  components: rustfmt

            - name: Build Tool
              run: cargo build --release

            - name: Run (Note)
              run: ./target/release/fnote note C4

            - name: Run (MIDI)
              run: ./target/release/fnote midi 60

            - name: Run (Frequency)
              run: ./target/release/fnote freq 261.63
